apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 3
  selector:
    matchLabels: { app: event-service }
  template:
    metadata:
      labels: { app: event-service }
    spec:
      initContainers:
        - name: wait-postgres
          image: postgres:16-alpine
          command: ["sh", "-c", "until pg_isready -h postgres -U postgres; do sleep 2; done"]
      containers:
        - name: event-service
          image: event-service:lab
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:lab@postgres:5432/events
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector: { app: event-service }
  ports:
    - port: 3000
